services:
  # Frontend (Next.js)
  frontend:
    image: node:18-alpine
    container_name: bitebase-frontend-dev
    working_dir: /app
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://api:8000
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm install && npm run dev"]
    depends_on:
      - api
    restart: unless-stopped

  # FastAPI Backend
  api:
    image: python:3.11-slim
    container_name: bitebase-api-dev
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=development
    volumes:
      - ./apps/api:/app
    ports:
      - "8000:8000"
    command: ["sh", "-c", "pip install -r requirements.txt && python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]
    restart: unless-stopped

  # PostgreSQL (for development)
  postgres:
    image: postgres:15-alpine
    container_name: bitebase-postgres-dev
    environment:
      POSTGRES_USER: bitebase
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: bitebase_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis (for development)
  redis:
    image: redis:7-alpine
    container_name: bitebase-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped

volumes:
  postgres_dev_data:
  redis_dev_data: