services:
  api:
    image: python:3.11-slim
    container_name: bitebase-api
    working_dir: /app
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://bitebase:password123@postgres:5432/bitebase
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=production
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    command: ["sh", "-c", "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4"]

  postgres:
    image: postgres:15-alpine
    container_name: bitebase-postgres
    environment:
      POSTGRES_USER: bitebase
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bitebase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: bitebase-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: