# Simple Docker test for BiteBase backend
version: '3.8'

services:
  # Simple backend test
  backend-test:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
      target: production
    container_name: bitebase-backend-test
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOSTNAME=0.0.0.0
    ports:
      - "3001:3001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  default:
    name: bitebase-test-network