services:
  # BiteBase Production Backend API (Enhanced with SaaS Features)
  - type: web
    name: bitebase-production-backend
    env: docker
    dockerfilePath: ./apps/backend/Dockerfile
    plan: standard
    region: oregon
    buildCommand: echo "Building with Docker"
    startCommand: node server-production.js
    healthCheckPath: /health
    envVars:
      # Core Configuration
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOSTNAME
        value: 0.0.0.0

      # Database Configuration
      - key: DATABASE_URL
        value: postgresql://bitebasedb_staging_owner:npg_vzp02ERAaXoQ@ep-damp-tooth-a4orgq86-pooler.us-east-1.aws.neon.tech/bitebasedb_staging?sslmode=require
      - key: REDIS_URL
        sync: false  # Set in Render dashboard

      # Security Configuration (Set these in Render dashboard for security)
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false

      # CORS Configuration
      - key: CORS_ORIGIN
        value: https://beta.bitebase.app,https://bitebase.app,https://bitebase-frontend.onrender.com,http://localhost:3000
      - key: NEXT_PUBLIC_SITE_URL
        value: https://beta.bitebase.app

      # AI Configuration
      - key: AI_MODE
        value: api
      - key: AI_FALLBACK_ENABLED
        value: true
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false

      # Payment Processing
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false

      # Email Services
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        value: noreply@bitebase.app

      # External APIs
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: MAPBOX_ACCESS_TOKEN
        value: pk.eyJ1Ijoia2hpd25pdGkiLCJhIjoiY203cm1oaWtyMWI4ejJpcHVuN2U2bHB6MiJ9.w9KWAvFEvF7bCdX-8Povkg

      # Monitoring and Analytics
      - key: SENTRY_DSN
        sync: false
      - key: GOOGLE_ANALYTICS_ID
        sync: false
      - key: DATADOG_API_KEY
        sync: false

      # Rate Limiting
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: RATE_LIMIT_PREMIUM_MAX
        value: 1000

      # File Storage
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET
        sync: false
      - key: AWS_REGION
        value: us-east-1

      # Legacy Support
      - key: AGENT_FASTAPI_URL
        value: https://bitebase-ai-agents.onrender.com
      - key: AGENT_GATEWAY_URL
        value: https://bitebase-ai-gateway.onrender.com

  # BiteBase Backend API (Legacy - Express.js)
  - type: web
    name: bitebase-backend-api
    env: node
    plan: starter
    buildCommand: cd apps/backend && npm ci && npm run build
    startCommand: cd apps/backend && npm run express:start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://bitebasedb_staging_owner:npg_vzp02ERAaXoQ@ep-damp-tooth-a4orgq86-pooler.us-east-1.aws.neon.tech/bitebasedb_staging?sslmode=require
      - key: CORS_ORIGIN
        value: https://beta.bitebase.app,https://bitebase.app,http://localhost:3000
      - key: AGENT_FASTAPI_URL
        value: https://bitebase-ai-agents.onrender.com
      - key: AGENT_GATEWAY_URL
        value: https://bitebase-ai-gateway.onrender.com

  # BiteBase Strapi CMS (Optional Admin Interface)
  - type: web
    name: bitebase-strapi-cms
    env: node
    plan: starter
    buildCommand: cd apps/backend && npm ci && npm run build
    startCommand: cd apps/backend && npm run start
    healthCheckPath: /admin
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://bitebasedb_staging_owner:npg_vzp02ERAaXoQ@ep-damp-tooth-a4orgq86-pooler.us-east-1.aws.neon.tech/bitebasedb_staging?sslmode=require
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_HOST
        value: ep-damp-tooth-a4orgq86-pooler.us-east-1.aws.neon.tech
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_NAME
        value: bitebasedb_staging
      - key: DATABASE_USERNAME
        value: bitebasedb_staging_owner
      - key: DATABASE_PASSWORD
        value: npg_vzp02ERAaXoQ
      - key: DATABASE_SSL
        value: true
      - key: DATABASE_SSL_REJECT_UNAUTHORIZED
        value: false
      - key: APP_KEYS
        value: 2ebuMok3H/O96/o1n/nOyg==,mLN9bGnz5IIzz0tR81ng8g==,vxFi1WuR/zifZJpZkZWVEw==,zr61pBkrMFUG80JQv6L1CA==
      - key: API_TOKEN_SALT
        value: 0tzHD0jdayW/8WIYX0vIyA==
      - key: ADMIN_JWT_SECRET
        value: pwnD8hb/0xTrUxY8KCHOTw==
      - key: TRANSFER_TOKEN_SALT
        value: CppdRmSl7U299fT06yUgNg==
      - key: JWT_SECRET
        value: 4RnZ3V+sClxdkd2xjgYj/Q==
      - key: CORS_ORIGIN
        value: https://beta.bitebase.app,https://bitebase.app,http://localhost:3000
      - key: STRAPI_ADMIN_MAPBOX_ACCESS_TOKEN
        value: pk.eyJ1Ijoia2hpd25pdGkiLCJhIjoiY203cm1oaWtyMWI4ejJpcHVuN2U2bHB6MiJ9.w9KWAvFEvF7bCdX-8Povkg

  # BiteBase AI Agents (Python FastAPI)
  - type: web
    name: bitebase-ai-agents
    env: python
    plan: starter
    buildCommand: cd agent && pip install -r requirements.txt
    startCommand: cd agent && python run_server.py
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: RELOAD
        value: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: DATABASE_URL
        value: postgresql://bitebasedb_staging_owner:npg_vzp02ERAaXoQ@ep-damp-tooth-a4orgq86-pooler.us-east-1.aws.neon.tech/bitebasedb_staging?sslmode=require

  # BiteBase AI Gateway (Node.js)
  - type: web
    name: bitebase-ai-gateway
    env: node
    plan: starter
    buildCommand: cd agent && npm ci
    startCommand: cd agent && node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
