# BiteBase Backend - Cloudflare Workers Configuration

name = "bitebase-backend"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Worker configuration
[env.production]
name = "bitebase-backend-prod"
route = { pattern = "api.bitebase.app/*", zone_name = "bitebase.app" }

[env.staging]
name = "bitebase-backend-staging"

# Environment variables (set via wrangler secret put)
[vars]
NODE_ENV = "production"
API_VERSION = "1.0.0"
CORS_ORIGIN = "*"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "900000"

# KV Namespaces for caching and sessions
[[kv_namespaces]]
binding = "CACHE"
id = "your-cache-namespace-id"
preview_id = "your-cache-preview-id"

[[kv_namespaces]]
binding = "SESSIONS"
id = "your-sessions-namespace-id"
preview_id = "your-sessions-preview-id"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "bitebase-production"
database_id = "your-database-id"

# R2 Storage for file uploads
[[r2_buckets]]
binding = "STORAGE"
bucket_name = "bitebase-uploads"
preview_bucket_name = "bitebase-uploads-preview"

# Durable Objects for real-time features
[[durable_objects.bindings]]
name = "CHAT_ROOMS"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

# Analytics Engine for logging
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# Queue for background tasks
[[queues.producers]]
binding = "TASK_QUEUE"
queue = "bitebase-tasks"

[[queues.consumers]]
queue = "bitebase-tasks"
max_batch_size = 10
max_batch_timeout = 30

# Build configuration
[build]
command = "npm run build:worker"

# Limits and performance
[limits]
cpu_ms = 50000

# Custom domains
[env.production.route]
pattern = "api.bitebase.app/*"
zone_name = "bitebase.app"

# Development configuration
[env.development]
name = "bitebase-backend-dev"
vars = { NODE_ENV = "development", CORS_ORIGIN = "http://localhost:3000" }