# Render.com deployment configuration for BiteBase FastAPI Backend
services:
  - type: web
    name: bitebase-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: bitebase-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: bitebase-redis
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.com,https://bitebase.app
      - key: SENTRY_DSN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_BUCKET_NAME
        value: bitebase-uploads
      - key: AWS_REGION
        value: us-east-1

databases:
  - name: bitebase-db
    databaseName: bitebase
    user: bitebase_user
    plan: starter

services:
  - type: redis
    name: bitebase-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru